language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -U flake8
  - pip install -U pytest
  - pip install -U pytest-cov
  - pip install -U pytest-mock
  - pip install -U coveralls
# command to run tests
script:
  - flake8 --max-line-length=120 --max-complexity=10 --statistics
  - py.test --doctest-modules --cov-report term-missing --cov=ciuy
after_success:
  - coveralls
