language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -U nose2
  - pip install -U coveralls
  - pip install -U pyyaml
# command to run tests
script:
  - nose2 --with-coverage
after_success:
    - coveralls
